Feature/strategy
mmic-collaboration/mmic-architecture-repository pull request #43
Opened 2024-07-22 15:22 UTC by iandelamare

2024-07-24 07:43 UTC, timothygalvin requested changes
Hi @iandelamare , thanks for the model updates, filling out nicely,

Comments:

1. (MAJOR) Energy Mix not clearly defined as a Business Object, or type of a 'thing'. It should be possible to clearly define what an instance of this is, for example.  Maybe just needs more definition.  A simple solution would be to re-use the"Generation Mix"  data structure on the National Grid APIand add a link in the object description: https://carbon-intensity.github.io/api-definitions/?shell#generation.  Also, at what point in time does the energy mix apply to the energy event?
2. (MAJOR) Plant and Location look like duplicates in other domains (PLANT domain for example).  Are they needed?  Asset location is all we need to position the energy event, then we can .  Unless there is a specific requirement for Plant and Location, i would remove them.  this will also simplify the model.
4. (MAJOR) Missing descriptions for Energy Event Type, Carbon Intensity (if we decide to keep it)
5. (Minor) we have an outstanding question of how we align time period of Carbon Intensity to the time period of the Energy Event.  Happy to raise this in a separate story, but the model wont work until we fix this.
6. (Minor) I would create a domain interaction between PLANET.Asset and PROCESS.Physical Asset.  this allows you to hold only asset sustainability information in  PLANET domain.  Asset Location may also drop out as well, depending on whats in it that you need for the carbon dashboard.
7. (Minor) is Energy Event a 'type of' Energy Event Type?
8. (Minor) BMS Event might be more simply represented as an entry in a list of possible event types within Energy Event Type, i.e. in the description.  this way you delegate the complexity of the subtyping to the LDM.
9. (Observation) After talking to Eviden, i am now convinced that "Carbon Emission", ironically, does not belong in PLANET Domain :)

2024-07-25 08:38 UTC, iandelamare commented
> Hi @iandelamare , thanks for the model updates, filling out nicely,
> 
> Comments:
> 
> 1. (MAJOR) Energy Mix not clearly defined as a Business Object, or type of a 'thing'. It should be possible to clearly define what an instance of this is, for example.  Maybe just needs more definition.  A simple solution would be to re-use the"Generation Mix"  data structure on the National Grid APIand add a link in the object description: https://carbon-intensity.github.io/api-definitions/?shell#generation.
> 2. (MAJOR) At what point in time does the energy mix apply to the energy event?
> 3. (MAJOR) Plant and Location look like duplicates in other domains (PLANT domain for example).  Are they needed?  Asset location is all we need to position the energy event, then we can .  Unless there is a specific requirement for Plant and Location, i would remove them.  this will also simplify the model.
> 4. (MAJOR) Missing descriptions for Energy Event Type, Carbon Intensity (if we decide to keep it)
> 5. (Minor) we have an outstanding question of how we align time period of Carbon Intensity to the time period of the Energy Event.  Happy to raise this in a separate story, but the model wont work until we fix this.
> 6. (Minor) I would create a domain interaction between PLANET.Asset and PROCESS.Physical Asset.  this allows you to hold only asset sustainability information in  PLANET domain.  Asset Location may also drop out as well, depending on whats in it that you need for the carbon dashboard.
> 7. (Minor) is Energy Event a 'type of' Energy Event Type?
> 8. (Minor) BMS Event might be more simply represented as an entry in a list of possible event types within Energy Event Type, i.e. in the description.  this way you delegate the complexity of the subtyping to the LDM.
> 9. (Observation) After talking to Eviden, i am now convinced that "Carbon Emission", ironically, does not belong in PLANET Domain :)

Responses:
1.	Don’t understand the review comment about Energy Mix “not clearly defined as a business object”. It is a business object and it has a description. As per your suggestion I have included the link to the API
2.	Re: at what point does energy mix apply to the energy event – whenever the API is called – I would assume in designing the services this would be resolved.
3.	Agree re: PLANT and LOCATION – expect if there are multiple PLANTS that are the focus. Have left this for now – need to answer this question.
4.	Carbon Intensity – no description: would have thought this was self describing but have included a description for consistency; have updated Energy Event Type description
5.	Agree we need to investigate the time alignment on events – would have thought this is a separate story when we investigate services
6.	No idea how to create a domain interaction
7.	“type of” is a very generic term – I was trying to be more specific – up there with “contains” or “is”
8.	I think when we explore the services we may be in a position to resolve this
9.	There is no “Carbon Emission” entity in the data model – this is calculated as part of a service I would have thought and may sit in another domain although I would have thought the service would sit in PLANET domain

2024-07-25 09:40 UTC, timothygalvin commented
added changes as per teams exchange to close off comments 1 thru 4

2024-07-25 09:41 UTC, timothygalvin approved these changes

2024-07-25 09:42 UTC, merged